import Head from "next/head";
import Content from "../components/Content";
import LastArticle from "../components/LastArticle";
import Slider from "../components/Slider";
import { client } from "/lib/sanityClient";

export default function Home({ data,articles }) {
 
  return (
    <div className="max-w-6xl p-3 lg:p-8 mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className=" grid grid-cols-6 mx-auto gap-3">
        <Slider articles={articles}/>
        <LastArticle />
      </div>

      <Content data={data} />
    </div>
  );
}

export const getServerSideProps = async () => {
  const query = `
  *[_type=="post"]{
    _id,
    title,
    description,
    mainImage,
    slug,
    image,
    author->{
    image,name,bio
  }
  }
  `;
  const lastArticles=`
  *[_type == "post" ]|order(_createdAt asc)[0..2]
  `
  const data = await client.fetch(query);
  const articles=await client.fetch(lastArticles)
  
  return {
    props: {
      data,
      articles
    },
  };
};
